# Generated by Django 3.2.18 on 2023-03-07 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lolin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classname',
            name='name',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='className',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='className', to='lolin.classname'),
        ),
    ]
